name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - "**.md"

env:
  GO111MODULE: on

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: make build

      - name: Update
        run: ./bin/tldr --update

      - name: Run tests with coverage report
        run: make test

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v3
        with:
          name: codecov-atomic
          files: ./coverage.txt
          flags: unit
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
